
spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    password: 123456
    username: admin
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
#      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trade: false
        web-allow-others: false